export const carListData = [
  {
    id: 1,
    imgUrl: 'https://i.ibb.co/cyvcpfF/uberx.png',
    service: 'CaboX',
    category: 'Economy',
    multiplier: 1,
    ratePerKm: 12,
    maxPassengers: 4,
    description: 'Affordable everyday rides',
    eta: '3 min',
  },
  {
    id: 2,
    imgUrl: 'https://i.ibb.co/YDYMKny/uberxl.png',
    service: 'CaboXL',
    category: 'Extra Space',
    multiplier: 1.5,
    ratePerKm: 18,
    maxPassengers: 6,
    description: 'More space for groups',
    eta: '5 min',
  },
  {
    id: 3,
    imgUrl: 'https://i.ibb.co/Xx4G91m/uberblack.png',
    service: 'CaboLux',
    category: 'Luxury',
    multiplier: 2,
    ratePerKm: 25,
    maxPassengers: 4,
    description: 'Premium black car service',
    eta: '7 min',
  },
  {
    id: 4,
    imgUrl: 'https://i.ibb.co/cyvcpfF/uberx.png',
    service: 'CaboComfort',
    category: 'Comfort',
    multiplier: 1.25,
    ratePerKm: 15,
    maxPassengers: 4,
    description: 'Extra comfort and legroom',
    eta: '4 min',
  },
  {
    id: 5,
    imgUrl: 'https://i.ibb.co/1nStPWT/uberblacksuv.png',
    service: 'CaboSUV',
    category: 'Premium SUV',
    multiplier: 2.5,
    ratePerKm: 30,
    maxPassengers: 7,
    description: 'Luxury SUV for large groups',
    eta: '8 min',
  },
];
