export const hotelListData = [
  {
    id: 1,
    name: 'The Grand Azure',
    address: 'Marine Drive, Mumbai',
    location: 'Mumbai',
    coordinates: [72.8233, 18.9438],
    price: 4500,
    rating: 4.8,
    reviewCount: 1243,
    stars: 5,
    amenities: ['Pool', 'Spa', 'WiFi', 'Restaurant', 'Gym', 'Parking'],
    imgUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&h=400&fit=crop',
    description: 'Experience luxury at The Grand Azure with stunning sea views along the iconic Marine Drive.',
    tag: 'Best Seller',
    distanceFromCenter: '0.3 km',
    type: 'Luxury',
    baseRate: 4500,
  },
  {
    id: 2,
    name: 'Cabotel Cityscape',
    address: 'Connaught Place, New Delhi',
    location: 'New Delhi',
    coordinates: [77.2195, 28.6329],
    price: 2800,
    rating: 4.5,
    reviewCount: 876,
    stars: 4,
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Conference Room', 'Gym'],
    imgUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&h=400&fit=crop',
    description: 'Modern business hotel in the heart of Delhi, minutes from top attractions and business hubs.',
    tag: 'Popular',
    distanceFromCenter: '0.1 km',
    type: 'Business',
    baseRate: 2800,
  },
  {
    id: 3,
    name: 'Horizon Bay Resort',
    address: 'Calangute Beach, Goa',
    location: 'Goa',
    coordinates: [73.7519, 15.5491],
    price: 6200,
    rating: 4.9,
    reviewCount: 2104,
    stars: 5,
    amenities: ['Beach Access', 'Pool', 'Spa', 'WiFi', 'Restaurant', 'Bar', 'Water Sports'],
    imgUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&h=400&fit=crop',
    description: 'Wake up to the sound of waves at Horizon Bay Resort, Goa\'s premier beachfront destination.',
    tag: 'Top Rated',
    distanceFromCenter: '2.1 km',
    type: 'Resort',
    baseRate: 6200,
  },
  {
    id: 4,
    name: 'Heritage Palace Inn',
    address: 'Old City, Jaipur',
    location: 'Jaipur',
    coordinates: [75.8235, 26.9124],
    price: 3500,
    rating: 4.6,
    reviewCount: 654,
    stars: 4,
    amenities: ['Pool', 'WiFi', 'Restaurant', 'Heritage Tour', 'Spa', 'Parking'],
    imgUrl: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&h=400&fit=crop',
    description: 'Stay in a restored Rajput palace and experience the royal heritage of the Pink City.',
    tag: 'Heritage',
    distanceFromCenter: '0.8 km',
    type: 'Heritage',
    baseRate: 3500,
  },
  {
    id: 5,
    name: 'Skyline Suites Bangalore',
    address: 'MG Road, Bengaluru',
    location: 'Bengaluru',
    coordinates: [77.6172, 12.9762],
    price: 3200,
    rating: 4.4,
    reviewCount: 489,
    stars: 4,
    amenities: ['WiFi', 'Gym', 'Restaurant', 'Rooftop Bar', 'Conference', 'Parking'],
    imgUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&h=400&fit=crop',
    description: 'Contemporary suites with panoramic city views, ideal for tech professionals and leisure travelers.',
    tag: 'Business Pick',
    distanceFromCenter: '0.5 km',
    type: 'Business',
    baseRate: 3200,
  },
  {
    id: 6,
    name: 'Mountain Mist Retreat',
    address: 'Cart Road, Shimla',
    location: 'Shimla',
    coordinates: [77.1734, 31.1048],
    price: 2200,
    rating: 4.7,
    reviewCount: 932,
    stars: 4,
    amenities: ['Mountain View', 'WiFi', 'Restaurant', 'Fireplace', 'Trekking Tours'],
    imgUrl: 'https://images.unsplash.com/photo-1586375300773-8384e3e4916f?w=600&h=400&fit=crop',
    description: 'Nestled in the Himalayas, this cozy retreat offers breathtaking views and tranquil mountain air.',
    tag: 'Scenic',
    distanceFromCenter: '1.2 km',
    type: 'Resort',
    baseRate: 2200,
  },
];
